from __future__ import annotations

from typing import Dict, List, Protocol


class UserRepository(Protocol):
    def load_all(self) -> Dict[str, dict]: ...

    def save_all(self, users: Dict[str, dict]) -> None: ...

    def save_one(self, user_id: str, payload: dict, expected_updated_at: str | None = None) -> dict: ...


class SessionRepository(Protocol):
    def create(self, token: str, user_id: str, created_at: str, expires_at: str) -> None: ...

    def get(self, token: str) -> dict | None: ...

    def delete(self, token: str) -> bool: ...

    def revoke_user(self, user_id: str) -> int: ...

    def revoke_prefix(self, prefix: str) -> int: ...

    def list_active(self) -> List[dict]: ...


class IssueRepository(Protocol):
    def load_all(self) -> List[dict]: ...

    def save_all(self, issues: List[dict]) -> None: ...

    def get_one(self, issue_id: str) -> dict | None: ...

    def save_one(self, payload: dict) -> dict: ...


class WorkOrderRepository(Protocol):
    def load_all(self) -> List[dict]: ...

    def save_all(self, orders: List[dict]) -> None: ...

    def get_one(self, order_id: str) -> dict | None: ...

    def save_one(self, payload: dict) -> dict: ...
